# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yoonyoung Cho
email: yoonyoung.cho@students.olin.edu 
address: 1000 Olin Way, Needham, Ma
phone: (+1) 213-220-3492
description: > # this means to ignore newlines until "baseurl:"
    Yoonyoung Cho's Portfolio Page
baseurl: "" # the subpath of your site, e.g. /blog
github_username: yycho0108
# Build settings
markdown: kramdown
